---

name: CI
"on": [push, pull_request]

permissions:
  id-token: write
  contents: read
  attestations: read

env:
  ZIG_VERSION: 0.13.0

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu, macos]
        mode: ["fast", "safe", "small", "off"]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        run: zig build --release=${{ matrix.mode }} --verbose --summary all
      - name: Test
        run: zig build test --release=${{ matrix.mode }} --summary all

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Install kcov
        run: |
          sudo apt-get update
          sudo apt-get install -y kcov

      - name: Generate coverage
        run: zig build coverage --summary all

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          directory: kcov-out/kcov-merged
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Format
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"

    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check .

  release:
    needs: [test]
    permissions:
      contents: write
      id-token: write
      attestations: write

    if: github.repository_owner == 'charlesrocket' && startsWith(github.ref, 'refs/tags/')

    uses: ./.github/workflows/cd.yml
    with:
      tag_name: ${{ github.ref_name }}
